variable "Name" {}
variable "Created_by" {}
variable "Dept" {}
variable "Env" {}
variable "vpc_id" {}
variable "instance_type" {}
variable "user" {}
variable "zone_id" {}
variable "domain" {}
variable "record" {}
