variable "Name" {}
variable "Created_by" {}
variable "Dept" {}
variable "Env" {}
variable "vpc" {}
variable "instance_type" {}
variable "user" {}
variable "zone_id" {}
variable "domain" {}
variable "record" {}
variable "ami" {}
variable "key_name" {}